import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import PrelineScriptWrapper from './components/PrelineScriptWrapper';
import AppLayout from './components/AppLayout';
import { SidebarProvider } from './components/SidebarContext';
import ThemeProvider from './components/ThemeProvider';

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} antialiased`}
      >
        <ThemeProvider>
          <SidebarProvider>
            <AppLayout>
              {children}
            </AppLayout>
          </SidebarProvider>
        </ThemeProvider>
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}
